name: dev_test
version: 1.0.1+1
description: Test utilities for dart and flutter packages on top of test_api package.
repository: https://github.com/tekartik/dev_test.dart/tree/master/dev_test

environment:
  sdk: ^3.11.0

dependencies:
  # flutter 3.41 pinned to 0.7.10
  test_api: '>=0.7.10 <2.0.0'
  test_core: '>=0.6.16 <2.0.0'

  matcher: '>=0.12.16 <2.0.0'
  dev_build: '>=1.1.5+3 <3.0.0'
  process_run: '>=1.3.2 <3.0.0'
  pub_semver: '>=2.1.4 <4.0.0'
  yaml: '>=3.1.2 <5.0.0'
  path: '>=1.9.0 <3.0.0'
  meta: '>=1.9.0 <3.0.0'
  pool: '>=1.5.2 <3.0.0'
  args: '>=2.7.0 <4.0.0'
  synchronized: '>=3.4.0+1 <5.0.0'
dev_dependencies:
  test: '>=1.31.1 <3.0.0'
  build_runner: '>=2.15.0'
  build_test: '>=3.5.15'
  build_web_compilers: '>=4.4.19'
  lints: '>=6.1.0'

