name: dev_test_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: ^3.9.0

dev_dependencies:
  path: '>=1.8.3'
  dev_test: '>=0.16.2-1'
  dev_build: '>=0.16.2-1'
  lints: '>=2.1.1'

dependency_overrides:
  dev_test:
    path: ../dev_test
  dev_build:
    path: ../dev_build
